.*/fnmsub.h.s: Assembler messages:
.*/fnmsub.h.s:1: Error.*
.*/fnmsub.h.s:2: Error.*
.*/fnmsub.h.s:3: Error.*
.*/fnmsub.h.s:4: Error.*
.*/fnmsub.h.s:5: Error.*
.*/fnmsub.h.s:6: Error.*
.*/fnmsub.h.s:7: Error.*
.*/fnmsub.h.s:8: Error.*
.*/fnmsub.h.s:9: Error.*
.*/fnmsub.h.s:10: Error.*
.*/fnmsub.h.s:11: Error.*
.*/fnmsub.h.s:12: Error.*
.*/fnmsub.h.s:13: Error.*
.*/fnmsub.h.s:14: Error.*
.*/fnmsub.h.s:15: Error.*
.*/fnmsub.h.s:16: Error.*
.*/fnmsub.h.s:17: Error.*
